POST http://localhost:3030/carro
Content-Type : application/json

{
    "Modelo" : "Palio",
    "Marca" : "Fiat", 
    "Placa" : "857-ADS", 
    "Ano" : 2013, 
    "Cor" : "Preto", 
    "mostorista" : "7777777777"
}

###
GET http://localhost:3030/carros

###
DELETE http://localhost:3040/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDUEYiOiI5OTk5OTk5OTk5OSIsIkVtYWlsIjoidGhpYWdvQGdtYWlsLmNvbSIsIlNlbmhhIjoiJDJiJDEwJENrMlZaZXZuUUlEblVRc24uMGEvdk9MZ3VJUEpHalowTFRSQVRDQnBtME1WbEdnbmh4SENLIiwiTm9tZSI6IlRoaWFnbyIsIlRlbGVmb25lIjoiODc5OTY2NDU2MzAiLCJDcmlhZG9FbSI6IjIwMjItMDUtMzBUMDE6Mzc6NTUuMTgxWiIsIkF0dWFsaXphZG9FbSI6IjIwMjItMDYtMDRUMDE6MDY6MTEuNzgzWiIsIlJlbW92aWRvRW0iOm51bGwsImlhdCI6MTY1NDMwNjUzM30.LpUMyhw3es_Korg21Q4JiJIoa3K6mt2URIO466h901U"
}
###
POST http://localhost:3040/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDUEYiOiI5OTk5OTk5OTk5OSIsIkVtYWlsIjoidGhpYWdvQGdtYWlsLmNvbSIsIlNlbmhhIjoiJDJiJDEwJENrMlZaZXZuUUlEblVRc24uMGEvdk9MZ3VJUEpHalowTFRSQVRDQnBtME1WbEdnbmh4SENLIiwiTm9tZSI6IlRoaWFnbyIsIlRlbGVmb25lIjoiODc5OTY2NDU2MzAiLCJDcmlhZG9FbSI6IjIwMjItMDUtMzBUMDE6Mzc6NTUuMTgxWiIsIkF0dWFsaXphZG9FbSI6IjIwMjItMDYtMDRUMDE6MDY6MTEuNzgzWiIsIlJlbW92aWRvRW0iOm51bGwsImlhdCI6MTY1NDMwNjUzM30.LpUMyhw3es_Korg21Q4JiJIoa3K6mt2URIO466h901U"
}
###

POST http://localhost:3040/login
Content-Type: application/json

{
    "Email" : "thiago@gmail.com",
    "Senha" : "123456"
}

###
GET http://localhost:3030/passageiro/99999999999
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGhpYWdvIiwiaWF0IjoxNjU0MzA2MjAzLCJleHAiOjE2NTQzMDYyMTh9.URysLmvTmu9agEFClHSADOMinvzv5jp8tP1VO9xYBoE

###
PUT http://localhost:3030/passageiro/99999999999
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDUEYiOiI5OTk5OTk5OTk5OSIsIkVtYWlsIjoidGhpYWdvQGdtYWlsLmNvbSIsIlNlbmhhIjoiJDJiJDEwJENrMlZaZXZuUUlEblVRc24uMGEvdk9MZ3VJUEpHalowTFRSQVRDQnBtME1WbEdnbmh4SENLIiwiTm9tZSI6IlRoaWFnbyBIb3J0ZW5jaW8gU0lsdmEgZGUgTWVsbyIsIlRlbGVmb25lIjoiODc5OTY2NDU2MzAiLCJDcmlhZG9FbSI6IjIwMjItMDUtMzBUMDE6Mzc6NTUuMTgxWiIsIkF0dWFsaXphZG9FbSI6IjIwMjItMDUtMzBUMDM6MjM6NDQuOTEyWiIsIlJlbW92aWRvRW0iOm51bGwsImlhdCI6MTY1NDMwNDc2MCwiZXhwIjoxNjU0MzA0Nzc1fQ.G6ez4Cgoti8Cyx2nS10jkimLsllAo5i4TH_gX-4aS5I
Content-Type: application/json


{
    "Nome": "Thiago Hortencio",
    "Email": "thiago@gmail.com",
    "Telefone": "87996645630",
    "Senha": "123456"
}

###
GET http://localhost:3030/passageiro/99999999999
