POST http://localhost:3030/carro
Content-Type : application/json

{
    "Modelo" : "Gol",
    "Marca" : "Volkswagem", 
    "Placa" : "1312-ADS", 
    "Ano" : 2020, 
    "Assentos": 5,
    "Cor" : "Prata", 
    "CPF" : "1313131311"
}

###
GET http://localhost:3030/carros/98513354449
###
GET http://localhost:3030/carros/
###
GET http://localhost:3030/carro/9
###
PUT http://localhost:3030/carro/
Content-Type: application/json

{
    "Id": 9,
    "Modelo": "Chevet",
    "Marca": "Chevrolet",
    "Placa": "1312-ADS",
    "Ano": 2018,
    "Cor": "Lilás"
}
###
DELETE http://localhost:3030/carro/9
###
POST http://localhost:3030/motorista/
Content-Type: application/json

{
    "CPF": "1313131311",
    "Nome": "Thiago Hortencio",
    "Email": "vamo@gmail.com",
    "Telefone": "87996645630",
    "Senha": "123456" 
}
###
PUT http://localhost:3030/motorista/
Content-Type: application/json

{
    "Id": "13131313131",
    "Nome": "Thiago Hortencio",
    "Email": "vamos@gmail.com",
    "Telefone": "87996645630",
    "Senha": "123456" 
}
###
GET http://localhost:3030/motoristas/
###
GET http://localhost:3030/motorista/vamo@gmail.com
###
DELETE http://localhost:3030/motorista/13131313131
###
POST http://localhost:3030/passageiro
Content-Type: application/json

{
    "CPF": "1313131313",
    "Nome": "Thiago Hortencio",
    "Email": "vamo@gmail.com",
    "Telefone": "87996645630",
    "Senha": "123456" 
}
###
PUT http://localhost:3030/passageiro/
Content-Type: application/json

{
    "Id": "13131313131",
    "Nome": "Thiago Hortencio Silva",
    "Email": "vamos@gmail.com",
    "Telefone": "87996645630",
    "Senha": "123456" 
}
###
GET http://localhost:3030/passageiros/
###
GET http://localhost:3030/passageiro/vamo@gmail.com
###
DELETE http://localhost:3030/passageiro/13131313131
###
POST http://localhost:3030/endereco/
Content-Type: application/json

{
    "Logradouro": "Rua Prof. Irineu",
    "PontoReferencia": "Prox. Hospital das Clínicas",
    "cidadeId": 1597,
    "Numero": 984
}
###
PUT http://localhost:3030/endereco/
Content-Type: application/json

{
    "Id": 1,
    "Logradouro": "Rua Lourival Tavares Aguiar",
    "PontoReferencia": "Entrando na placa do Loteamento Sales",
    "cidadeId": 1505,
    "Numero": 24 
}
###
GET http://localhost:3030/enderecos/
###
GET http://localhost:3030/enderecos/23
###
GET http://localhost:3030/endereco/2
###
DELETE http://localhost:3030/endereco/7
###
POST http://localhost:3030/viagem/
Content-Type: application/json

{
    "HoraSaida": "2022-06-27T03:21:13.131Z",
    "Valor": 13.13,
    "DataIda": "2022-06-28T03:21:13.131Z",
    "motoristaId": "13131313131",
    "enderecoId": 4
}
###
GET http://localhost:3030/viagens/
###
GET http://localhost:3030/viagem/2
###
PUT http://localhost:3030/viagem/
Content-Type: application/json

{
    "Id": 1,
    "HoraSaida": "2022-06-27T04:21:13.131Z",
    "Valor": 13.13,
    "DataIda": "2022-06-28T03:21:13.131Z",
    "IsConcluido": false,
    "iniciadoEm": "2022-06-28T05:21:13.131Z",
    "concluidoEm": null,
    "avaliacao": null,
    "IsConcluidoPass": false,
    "iniciadoEmPass": "2022-06-28T05:21:13.131Z",
    "concluidoEmPass": null,
    "avaliacaoPass": null,
    "passageiroId": "13131313131",
    "motoristaId": "13131313131"
}
###
DELETE http://localhost:3040/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDUEYiOiI5OTk5OTk5OTk5OSIsIkVtYWlsIjoidGhpYWdvQGdtYWlsLmNvbSIsIlNlbmhhIjoiJDJiJDEwJENrMlZaZXZuUUlEblVRc24uMGEvdk9MZ3VJUEpHalowTFRSQVRDQnBtME1WbEdnbmh4SENLIiwiTm9tZSI6IlRoaWFnbyIsIlRlbGVmb25lIjoiODc5OTY2NDU2MzAiLCJDcmlhZG9FbSI6IjIwMjItMDUtMzBUMDE6Mzc6NTUuMTgxWiIsIkF0dWFsaXphZG9FbSI6IjIwMjItMDYtMDRUMDE6MDY6MTEuNzgzWiIsIlJlbW92aWRvRW0iOm51bGwsImlhdCI6MTY1NDMwNjUzM30.LpUMyhw3es_Korg21Q4JiJIoa3K6mt2URIO466h901U"
}
###
POST http://localhost:3040/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDUEYiOiI5OTk5OTk5OTk5OSIsIkVtYWlsIjoidGhpYWdvQGdtYWlsLmNvbSIsIlNlbmhhIjoiJDJiJDEwJENrMlZaZXZuUUlEblVRc24uMGEvdk9MZ3VJUEpHalowTFRSQVRDQnBtME1WbEdnbmh4SENLIiwiTm9tZSI6IlRoaWFnbyIsIlRlbGVmb25lIjoiODc5OTY2NDU2MzAiLCJDcmlhZG9FbSI6IjIwMjItMDUtMzBUMDE6Mzc6NTUuMTgxWiIsIkF0dWFsaXphZG9FbSI6IjIwMjItMDYtMDRUMDE6MDY6MTEuNzgzWiIsIlJlbW92aWRvRW0iOm51bGwsImlhdCI6MTY1NDMwNjUzM30.LpUMyhw3es_Korg21Q4JiJIoa3K6mt2URIO466h901U"
}
###
POST http://localhost:3040/login
Content-Type: application/json

{
    "Email" : "vamo@gmail.com",
    "Senha" : "123456"
}

###
GET http://localhost:3030/passageiro/99999999999
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGhpYWdvIiwiaWF0IjoxNjU0MzA2MjAzLCJleHAiOjE2NTQzMDYyMTh9.URysLmvTmu9agEFClHSADOMinvzv5jp8tP1VO9xYBoE

###
PUT http://localhost:3030/passageiro/99999999999
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDUEYiOiI5OTk5OTk5OTk5OSIsIkVtYWlsIjoidGhpYWdvQGdtYWlsLmNvbSIsIlNlbmhhIjoiJDJiJDEwJENrMlZaZXZuUUlEblVRc24uMGEvdk9MZ3VJUEpHalowTFRSQVRDQnBtME1WbEdnbmh4SENLIiwiTm9tZSI6IlRoaWFnbyBIb3J0ZW5jaW8gU0lsdmEgZGUgTWVsbyIsIlRlbGVmb25lIjoiODc5OTY2NDU2MzAiLCJDcmlhZG9FbSI6IjIwMjItMDUtMzBUMDE6Mzc6NTUuMTgxWiIsIkF0dWFsaXphZG9FbSI6IjIwMjItMDUtMzBUMDM6MjM6NDQuOTEyWiIsIlJlbW92aWRvRW0iOm51bGwsImlhdCI6MTY1NDMwNDc2MCwiZXhwIjoxNjU0MzA0Nzc1fQ.G6ez4Cgoti8Cyx2nS10jkimLsllAo5i4TH_gX-4aS5I
Content-Type: application/json


{
    "Nome": "Thiago Hortencio",
    "Email": "thiago@gmail.com",
    "Telefone": "87996645630",
    "Senha": "123456"
}

###
GET http://localhost:3030/passageiro/99999999999

###
GET http://localhost:3030/passageiros/
###
GET http://localhost:3030/cidades
###
GET http://localhost:3030/estados
